BSU.SetupCommand("nothing", function(cmd)
	cmd:SetDescription("Do nothing to a player")
	cmd:SetFunction(function(self, _, targets)
		self:BroadcastActionMsg("%caller% did nothing to %targets%", { targets = targets })
	end)
	cmd:AddPlayersArg("targets", { default = "^", filter = true })
end)
